version: '3.8'

services:
  # Main application service
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/faqdb
      - REDIS_URL=redis://redis:6379

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# Persistent volume for MongoDB
volumes:
  mongodb_data: